spring:
  application:
    name: demcayniki-api
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  mail:
    from: "Demcayniki <${MAIL}>"
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  web:
    error:
      include-message: always

server:
  port: 8080

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

security:
  jwt:
    issuer: ${JWT_ISSUER:demcayniki-api}
    audience: ${JWT_AUDIENCE:demcayniki-clients}
    expiration-minutes: ${JWT_EXP_MINUTES:10}
    key-id: ${JWT_KID:dev-1}
    public-key-location: ${JWT_PUBLIC_KEY:classpath:keys/jwt_public.pem}

security-refresh:
  expiration-days: ${REFRESH_EXP_DAYS:14}
