#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/demcayniki
#    username: postgres
#    password: postgres
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 2
#      pool-name: local-hikari
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: false

logging:
  level:
    com.example.demcayniki: DEBUG

security:
  jwt:
    private-key-location: ${JWT_PRIVATE_KEY:classpath:keys/jwt_private.pem}
    public-key-location: ${JWT_PUBLIC_KEY:classpath:keys/jwt_public.pem}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


app:
  verification:
    hmac-secret: ${VERIFICATION_HMAC_SECRET}
  mail:
    from: "Demcayniki <${MAIL}>"